### ISSUE TITLE
SslServerHandler broken?

### ISSUE THREAD

**Issue by b-c-ds** [sensepost/mallet#15]
Bumping dependencies in the latest commit (#14) seems to have broken the `SslServerHandler`.
When I build from d123ac8be10d69ffb142958dc7abd9f698605fcd it works.

Latest master gives the exception: `failed to access class org.bouncycastle.asn1.DEROutputStream from class org.bouncycastle.cert.CertUtils`.

```
Aug 25, 2021 2:55:39 PM com.sensepost.mallet.ssl.AutoGeneratingContextSelector createKeyMaterial
INFO: Creating key material for redacted.whatever
Aug 25, 2021 2:55:39 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalAccessError: failed to access class org.bouncycastle.asn1.DEROutputStream from class org.bouncycastle.cert.CertUtils (org.bouncycastle.asn1.DEROutputStream and org.bouncycastle.cert.CertUtils are in unnamed module of loader 'app')
	at org.bouncycastle.cert.CertUtils.generateSig(Unknown Source)
	at org.bouncycastle.cert.CertUtils.generateFullCert(Unknown Source)
	at org.bouncycastle.cert.X509v3CertificateBuilder.build(Unknown Source)
	at com.sensepost.mallet.ssl.CertificateUtils.sign(CertificateUtils.java:120)
	at com.sensepost.mallet.ssl.AutoGeneratingContextSelector.createKeyMaterial(AutoGeneratingContextSelector.java:264)
	at com.sensepost.mallet.ssl.AutoGeneratingContextSelector$SslContextMapper.map(AutoGeneratingContextSelector.java:321)
	at com.sensepost.mallet.ssl.AutoGeneratingContextSelector.map(AutoGeneratingContextSelector.java:234)
	at com.sensepost.mallet.ssl.AutoGeneratingContextSelector.map(AutoGeneratingContextSelector.java:69)
	at io.netty.handler.ssl.SniHandler$AsyncMappingAdapter.map(SniHandler.java:165)
	at io.netty.handler.ssl.SniHandler$AsyncMappingAdapter.map(SniHandler.java:154)
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:97)
	at io.netty.handler.ssl.AbstractSniHandler.select(AbstractSniHandler.java:208)
	at io.netty.handler.ssl.AbstractSniHandler.decode(AbstractSniHandler.java:172)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:408)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:913)
	at com.sensepost.mallet.channel.SubChannel$SubChannelUnsafe$2.run(SubChannel.java:454)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

If you don't already have a Mallet CA, then running Mallet for the first time will fail as it tries to generate a CA cert.

**Comment by RoganDawes** [comment]
Fixed, thanks for the report.

**Comment by shuli1115** [comment]
@RoganDawes Hi Rogan, I met the same error when bump up to version 1.67, how did you fix this issue? Thanks!
